# Generated by Django 3.0.8 on 2020-07-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_move', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='comment',
            field=models.TextField(help_text='Any comments?', null=True),
        ),
        migrations.AlterField(
            model_name='moneysource',
            name='second_level_source',
            field=models.CharField(help_text='Source-second-level', max_length=200),
        ),
        migrations.AlterField(
            model_name='spendingkind',
            name='second_level_kind',
            field=models.CharField(help_text='Kind-second-level', max_length=200),
        ),
        migrations.AlterField(
            model_name='spendings',
            name='comment',
            field=models.TextField(help_text='Any comments?', null=True),
        ),
    ]
