# Generated by Django 3.0.8 on 2020-08-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_move', '0002_auto_20200731_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_field',
            field=models.DateField(default='2020-08-07'),
        ),
        migrations.AlterField(
            model_name='spendings',
            name='date_field',
            field=models.DateField(default='2020-08-07'),
        ),
    ]
