# Generated by Django 3.0.8 on 2020-09-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money_move', '0003_auto_20200807_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_level_cashkind', models.CharField(help_text='CashKind-first-level', max_length=200)),
                ('second_level_cashkind', models.CharField(help_text='CashKind-second-level', max_length=200)),
            ],
            options={
                'ordering': ['-first_level_cashkind'],
            },
        ),
        migrations.AlterField(
            model_name='income',
            name='date_field',
            field=models.DateField(default='2020-09-10'),
        ),
        migrations.AlterField(
            model_name='spendings',
            name='date_field',
            field=models.DateField(default='2020-09-10'),
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(default='2020-09-10')),
                ('ammount', models.FloatField(help_text='000.00')),
                ('comment', models.TextField(help_text='Any comments?', null=True)),
                ('cash_kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money_move.CashKind')),
            ],
            options={
                'ordering': ['-date_field'],
            },
        ),
    ]
