# Generated by Django 3.0.8 on 2020-10-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_move', '0004_auto_20200910_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='date_field',
            field=models.DateField(default='2020-10-14'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_field',
            field=models.DateField(default='2020-10-14'),
        ),
        migrations.AlterField(
            model_name='spendings',
            name='date_field',
            field=models.DateField(default='2020-10-14'),
        ),
    ]
