# Generated by Django 3.0.8 on 2020-10-23 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money_move', '0005_auto_20201014_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='purpose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='cash_kind_income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money_move.CashKind'),
        ),
        migrations.AddField(
            model_name='spendings',
            name='cash_kind_spending',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money_move.CashKind'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='date_field',
            field=models.DateField(default='2020-10-23'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_field',
            field=models.DateField(default='2020-10-23'),
        ),
        migrations.AlterField(
            model_name='spendings',
            name='date_field',
            field=models.DateField(default='2020-10-23'),
        ),
    ]
