# Generated by Django 3.0.8 on 2020-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_move', '0007_auto_20201113_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='date_field',
            field=models.DateField(default='2020-11-16'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_field',
            field=models.DateField(default='2020-11-16'),
        ),
        migrations.AlterField(
            model_name='spendings',
            name='date_field',
            field=models.DateField(default='2020-11-16'),
        ),
    ]
